name: on host workflow

on:
  push:
    branches: [ acap-build ]
  pull_request:

jobs:
  debian_and_ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install g++-aarch64-linux-gnu g++-arm-linux-gnueabihf
      - run: rustup show
      - run: cargo install --locked cargo-about@0.6.2
      - run: cargo install --locked --path crates/cargo-acap-build
      - run: make apps/hello_world/LICENSE
      - run: cargo-acap-build -- --package hello_world
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CARGO_TARGET_THUMBV7NEON_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
      - run: shasum target/aarch64/**